// ...existing code before emoji functionality...

// [Removed] All emoji conversion and preview code.
// (Ensure no functions or event listeners related to emoji picker remain)

// ...existing code continues...
